<?php

namespace App\Constants;

class Attributes extends CustomEnum
{
    const LIMIT = "limit";
    const PAGE = "page";
    const ID = "id";
    const USER = "user";
    const USER_ID = "user_id";
    const PHONE_NUMBER = "phone_number";
    const TYPE_NAME = "type_name";
    const EMAIL = "email";
    const VERIFIED_AT = "verified_at";
    const LAST_NAME = "last_name";
    const LTR = "ltr";
    const FIRST_NAME = "first_name";
    const MESSAGE = "message";
    const PASSWORD = "password";
    const CREATED_AT = "created_at";
    const ITEM_TYPE = "item_type";
    const DELETED_AT = "deleted_at";
    const DEFAULT = "default";
    const UPDATED_AT = "updated_at";
    const GO_TO = "go_to";
    const ITEM_ID = "item_id";
    const DAILY_TIPS = "daily_tips";
    const CAKES = "cakes";
    const NAME = "name";
    const BACKDROPS = "backdrops";
    const GENDER = "gender";
    const REMEMBER_TOKEN = "remember_token";
    const STATUS = "status";
    const TITLE = "title";
    const CONTENT = "content";
    const DATA = "data";
    const IMAGE = "image";
    const ORDER = "order";
    const PHOTOGRAPHERS = "photographers";
    const HOME = "home";
    const PROMOTIONS = "promotions";
    const ONBOARDING = "onboarding";
    const RTL = "rtl";
    const TYPE = "type";
    const MAXLENGTH = "maxlength";
    const LABEL = "label";
    const ATTRIBUTES = "attributes";
    const DIR = "dir";
    const TAB = "tab";
    const DESCRIPTION = "description";
    const ROWS = "rows";
    const HINT = "hint";
    const FEATURED_IMAGE = "featured_image";
    const CROP = "crop";
    const ASPECT_RATIO = "aspect_ratio";
    const PRIORITY = "priority";
    const STATUS_NAME = "status_name";
    const ALLOWS_NULL = "allows_null";
    const OPTIONS = "options";
    const URL = "url";
    const THUMBNAIL = "thumbnail";
    const IS_COMPRESSED = "is_compressed";
    const CATEGORY = "category";
    const POSTED_AT = "posted_at";
    const OFFER = "offer";
    const DATE = "date";
    const CODE = "code";
    const PRICE = "price";
    const PREFIX = "prefix";
    const SUFFIX = "suffix";
    const RATING = "rating";
    const USER_NAME = "user_name";
    const USER_IMAGE = "user_image";
    const PACKAGE_ID = "package_id";
    const SESSION_ID = "session_id";
    const COMMENT = "comment";

}
